name: "tfsuit GitHub Actions"
description: "Terraform customizable tool for defining your standards, styles, and naming conventions"
inputs:
  dir:
    description: "Whether the project is a module or a digital product (available values to pass are: | proj | mod |)"
    required: true
  config-json-path:
    description: "The TF project directory will be analyzed"
    required: true
  fail-on-not-compliant:
    description: "Whether to launch an exit 1 when it detects there are some rules that weren't accomplished"
    required: false
    default: "false"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.dir }}
    - ${{ inputs.config-json-path }}
    - ${{ inputs.fail-on-not-compliant }}
