name: "tfsuit"
description: "Terraform customizable tool for defining your standards, styles, and naming conventions"
inputs:
  dir:
    description: "Whether the project is a module or a digital product (available values to pass are: | proj | mod |)"
    required: true
  config_json_path:
    description: "The TF project directory will be analyzed"
    required: true
  fail_on_not_compliant:
    description: "Whether to launch an exit 1 when it detects there are some rules that weren't accomplished"
    required: false
    default: "false"
  docs_link:
    description: "Related documentation link to show when tfsuit fails because not compliant rules"
    required: false
    default: ""
outputs:
  compliant_vars:
    description: "A JSON list of compliant vars"
  not_complaint_vars:
    description: "A JSON list of not compliant vars"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.dir }}
    - ${{ inputs.config_json_path }}
    - ${{ inputs.fail_on_not_compliant }}
    - ${{ inputs.docs_link }}
branding:
  icon: "box"
  color: "gray-dark"
