name: "Tests"

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: install gsht
        run: |
          wget https://github.com/NekoOs/gsht.sh/releases/download/nightly/gsht.gsht
          sudo mv gsht.gsht /usr/local/bin/gsht
          sudo chmod a+x /usr/local/bin/gsht
      - name: transpile
        run: |
          gsht --input src/tfsuit.sh  --output tfsuit
          sudo mv tfsuit /usr/local/bin/tfsuit
          sudo chmod a+x /usr/local/bin/tfsuit
      - name: test
        run: tfsuit -c tfsuit.example.json -d .
