name: "Tests"

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: transpile
        run: |
          wget https://github.com/NekoOs/gsht.sh/releases/download/nightly/gsht
          chmod a+x gsht
          gsht /src/tfsuit.sh --output=tfsuit
